// <auto-generated />
using System;
using Billetera.BD.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Billetera.BD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251114043850_08")]
    partial class _08
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Billetera.BD.Datos.Entity.Billeteras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Billera_Admin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Billeteras");
                });

            modelBuilder.Entity("Billetera.BD.Datos.Entity.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BilleteraId")
                        .HasColumnType("int");

                    b.Property<string>("NumCuenta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "BilleteraId" }, "Cuenta_Billetera_UQ")
                        .IsUnique();

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("Billetera.BD.Datos.Entity.Moneda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodISO")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("ComisionPorcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Habilitada")
                        .HasColumnType("bit");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoMoneda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CodISO" }, "Moneda_CodISO_UQ")
                        .IsUnique();

                    b.ToTable("Monedas");
                });

            modelBuilder.Entity("Billetera.BD.Datos.Entity.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("MonedaTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Saldo_Anterior")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Saldo_Nuevo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TipoCuentaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoMovimientoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoCuentaId");

                    b.HasIndex("TipoMovimientoId");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("Billetera.BD.Datos.Entity.TipoCuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CuentaId")
                        .HasColumnType("int");

                    b.Property<bool>("EsCuentaDemo")
                        .HasColumnType("bit");

                    b.Property<int>("MonedaId")
                        .HasColumnType("int");

                    b.Property<string>("Moneda_Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TC_Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CuentaId");

                    b.HasIndex("MonedaId");

                    b.HasIndex(new[] { "Alias" }, "TipoCuenta_Alias_UQ")
                        .IsUnique();

                    b.ToTable("TiposCuentas");
                });

            modelBuilder.Entity("Billetera.BD.Datos.Entity.TipoMovimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoMovimientos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Ingreso de dinero a la cuenta",
                            Nombre = "Depósito",
                            Operacion = "suma"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Retiro de dinero de la cuenta",
                            Nombre = "Extraccion",
                            Operacion = "resta"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Movimiento que representa una transferencia a otra cuenta.",
                            Nombre = "Transferencia",
                            Operacion = "transferencia"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Compra realizada de un tipo de moneda a usuario o billetera.",
                            Nombre = "Compra",
                            Operacion = "resta"
                        });
                });

            modelBuilder.Entity("Billetera.BD.Datos.Entity.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BilleteraId")
                        .HasColumnType("int");

                    b.Property<long>("CUIL")
                        .HasColumnType("bigint");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BilleteraId");

                    b.HasIndex(new[] { "CUIL" }, "Usuarios_CUIL_UQ")
                        .IsUnique();

                    b.HasIndex(new[] { "Correo" }, "Usuarios_Correo_UQ")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Billetera.BD.Datos.Entity.Cuenta", b =>
                {
                    b.HasOne("Billetera.BD.Datos.Entity.Billeteras", "Billetera")
                        .WithMany()
                        .HasForeignKey("BilleteraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Billetera");
                });

            modelBuilder.Entity("Billetera.BD.Datos.Entity.Movimiento", b =>
                {
                    b.HasOne("Billetera.BD.Datos.Entity.TipoCuenta", "TipoCuenta")
                        .WithMany()
                        .HasForeignKey("TipoCuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Billetera.BD.Datos.Entity.TipoMovimiento", "TipoMovimiento")
                        .WithMany()
                        .HasForeignKey("TipoMovimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoCuenta");

                    b.Navigation("TipoMovimiento");
                });

            modelBuilder.Entity("Billetera.BD.Datos.Entity.TipoCuenta", b =>
                {
                    b.HasOne("Billetera.BD.Datos.Entity.Cuenta", "Cuenta")
                        .WithMany("TiposCuentas")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Billetera.BD.Datos.Entity.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuenta");

                    b.Navigation("Moneda");
                });

            modelBuilder.Entity("Billetera.BD.Datos.Entity.Usuarios", b =>
                {
                    b.HasOne("Billetera.BD.Datos.Entity.Billeteras", "Billetera")
                        .WithMany("Usuarios")
                        .HasForeignKey("BilleteraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Billetera");
                });

            modelBuilder.Entity("Billetera.BD.Datos.Entity.Billeteras", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Billetera.BD.Datos.Entity.Cuenta", b =>
                {
                    b.Navigation("TiposCuentas");
                });
#pragma warning restore 612, 618
        }
    }
}
